#include "StdTypes.h"
#include "Bit_Math.h"
#include "MemMap.h"
#include "MPORT.h"
#include "MPORT_LCFG.h"



MPORT_structPortPinDirAndMode_t MDIO_enuArrPinConfig[MPORT_NUM_OF_ALL_PINS] = 
{
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN}
};

