#include "StdTypes.h"
#include "Bit_Math.h"
#include "MemMap.h"
#include "MPORT.h"
#include "MPORT_LCFG.h"



MPORT_structPortPinDirAndMode_t MPORT_enuArrPinConfig[MPORT_NUM_OF_ALL_PINS] = 
{
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 0 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 1 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 2 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 3 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 4 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 5 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 6 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port A Pin 7 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port B Pin 0 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},     /* Port B Pin 1 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 2 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 3 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 4 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 5 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 6 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port B Pin 7 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 0 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 1 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 2 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 3 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 4 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 5 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 6 */
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLUP},      /* Port C Pin 7 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 0 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 1 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 2 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 3 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 4 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 5 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},      /* Port D Pin 6 */
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_INPUT_PULLDOWN}       /* Port D Pin 7 */
};

